<?php
// $Id$

/**
 * @file
 * Used to aggregate syndicated content (RSS, RDF, and Atom).
 */

/**
 * Denotes that a feed's items should never expire.
 */
//define('AGGREGATOR_CLEAR_NEVER', 0);



/**
 * Implements hook_custom_theme().
 * Hook appelé à chaque démarrage de Drupal, juste après l'activation du module, 
 * et avant toute autre opération
 * 
 */

//function bddprospection_custom_theme(){
//  
//  //Chargement du css customizé
//  
//}

//(drupal_get_path('module', 'bddprospection')


//drupal_add_css(drupal_get_path('module', 'bddprospection').'/css/bddprospection_maintheme.css', array
//  ('group' => CSS_SYSTEM +9999, 'preprocess' => FALSE));


/**
 * PATH
 */

// Récupération du dossier du module
$module_path=drupal_get_path('module', 'bddprospection');

//// Association d'un script contenu mon_module/scripts/script.js
//drupal_add_js($path . '/scripts/script.js');
//
//// Association d'une feuille de style contenu mon_module/styles/style.js
//drupal_add_css($path . '/styles/style.js');






/**
 * Implements hook_permission().
 */
function bddprospection_permission(){
  return array(
    'access bddprospection' => array('title' => t('Access bddprospection'))
);
}


/**
 * Implements hook_block_info().
 */
//Ici on explique à Drupal les différents blocs que l'on va créer


//function bddprospection_block_info() {
//  $blocks['current_posts'] = array(
//    'info' => t('Current posts'), //The name that will appear in the block list.
//    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
//  );
//  return $blocks;
//}




////LE MODULE DEPLOIE UN BLOC  -> ex: menu... sur le côté de la page
// function bddprospection_block(){
//   
//   
// }



 // DECLARER L'ADRESSE DES PAGES CONCERNEES PAR LE MODULE 
 // http://www.kolossaldrupal.org/docs/informer-drupal-de-lexistence-de-cette-nouvelle-fonction
/**
 * Implements hook_menu(). 
 */
function bddprospection_menu() {
$items = array();

$items['bddprospection/menu_principal'] = array(
  'title' => 'MENU PRINCIPAL',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('bddprospection_principal'),
  'access arguments' => array('access bddprospection'),
  'type' => MENU_CALLBACK,
  //'file' => 'bddprospection_menu_principal.inc',
);

$items['bddprospection/formulaire'] = array(
    'title' => 'AJOUTER UN NOUVEL APPEL',
    'page callback' => 'bddprospection_myform',
    'access arguments' => array('access bddprospection'),
    'type' => MENU_CALLBACK,
    //'file' => 'bddprospection_menu_principal.inc',////RAJOUTER
  );



$items['bddprospection/test'] = array(
    'title' => 'LISTE DES APPELS',
    'page callback' => 'bddprospection_liste_appel_btp',
    'access arguments' => array('access bddprospection'),
    'type' => MENU_CALLBACK,
    //'file' => 'bddprospection_menu_principal.inc',////RAJOUTER
  );



$items['bddprospection/gerer_prospecteurs'] = array(
    'title' => t('Gérer les prospecteurs'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bddprospection_gerer_prospecteurs'),
    //'page callback' => 'bddprospection_gerer_prospecteurs',
    'access arguments' => array('access bddprospection'),
    'type' => MENU_CALLBACK,
   
  );

$items['bddprospection/consulter_prospecteurs'] = array(
    'title' => t('Consulter les prospecteurs'),
    'page callback' => 'bddprospection_consulter_prospecteurs',
    'access arguments' => array('access bddprospection'),
    'type' => MENU_CALLBACK,
   
  );

$items['bddprospection/ajout_prospecteurs'] = array(
    'title' => t('Ajouter un prospecteur'),
    'page callback' => 'bddprospection_ajouter_prospecteurs',
    'access arguments' => array('access bddprospection'),
    'type' => MENU_CALLBACK,
   
  );

$items['bddprospection/maj_prospecteurs'] = array(
    'title' => t('Mettre à jour les données du prospecteur'),
    'page callback' => 'bddprospection_mettre_a_jour_prospecteurs',
    'access arguments' => array('access bddprospection'),
    'type' => MENU_CALLBACK,
   
  );

$items['bddprospection/supprimer_prospecteurs'] = array(
    'title' => t('Supprimer un prospecteur'),
    'page callback' => 'bddprospection_mettre_a_jour_prospecteurs',
    'access arguments' => array('access bddprospection'),
    'type' => MENU_CALLBACK,
   
  );







$items['bddprospection/gerer_entreprises'] = array(
    'title' => t('Gérer les entreprises'),
    'page callback' => 'bddprospection_gerer_entreprises',
    'access arguments' => array('access bddprospection'),
    'type' => MENU_CALLBACK,
   
  );

$items['bddprospection/gerer_contacts'] = array(
    'title' => t('Gérer les contacts'),
    'page callback' => 'bddprospection_gerer_contacts',
    'access arguments' => array('access bddprospection'),
    'type' => MENU_CALLBACK,
   
  );

$items['bddprospection/gerer_rappels'] = array(
    'title' => t('Gérer les rappels'),
    'page callback' => 'bddprospection_gerer_rappels',
    'access arguments' => array('access bddprospection'),
    'type' => MENU_CALLBACK,
   
  );

$items['bddprospection/gerer_appels'] = array(
    'title' => t('Gérer les appels'),
    'page callback' => 'bddprospection_gerer_appels',
    'access arguments' => array('access bddprospection'),
    'type' => MENU_CALLBACK,
   
  );


return $items;
}




















/*******************************************************************************
 * 
 ****************************  PAGE PRINCIPALE *********************************
 * 
********************************************************************************/

function bddprospection_principal(){
$content = drupal_get_form('bddprospection_principal_form');
return $content;
}

function bddprospection_principal_form(){

  //FIELD AJOUT APPEL
    $form['fieldset_ajout_appel'] = array (
        '#type' => 'fieldset',
        '#title' => 'Ajouter un appel',
        '#weight' => 0, 
        '#collapsible' => TRUE, 
        '#collapsed' => FALSE,
    );
    
    $form['fieldset_ajout_appel']['boutton_ajout_appel'] = array (
        '#value' => t('Accéder au formulaire'),
        '#type' => 'submit',
        '#submit' => array('bddprospection_action_ajouter_appel') 
    );

    
    
    
    
  //FIELD LISTE APPEL
  $form['fieldset_liste_appels'] = array (
      '#type' => 'fieldset',
      '#title' => 'Liste des appels',
      '#weight' => 1, 
      '#collapsible' => TRUE, 
      '#collapsed' => FALSE,
  );

  $form['fieldset_liste_appels']['boutton_liste_appels_tous'] = array (
      '#value' => t('Accéder à la liste des appels'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_liste_appel')  /////EN COURS
  );
  
  $form['fieldset_liste_appels']['boutton_liste_appels_BTP_BAA'] = array (
      '#value' => t('Appels BTP - BAA'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_liste_appels_BTP_BAA')  /////EN COURS
  );
  
  $form['fieldset_liste_appels']['boutton_liste_appels_CM'] = array (
      '#value' => t('Appels CM'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_liste_appel_CM')  /////JUSTE RAJOUTER
  );
   
  $form['fieldset_liste_appels']['boutton_liste_appels_IMS_ESEA'] = array (
      '#value' => t('Appels IMS - ESEA'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_liste_appels_IMS_ESEA')  /////JUSTE RAJOUTER
  );
  
  $form['fieldset_liste_appels']['boutton_liste_appels_ITI'] = array (
      '#value' => t('Appels ITI'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_liste_appels_ITI')  /////JUSTE RAJOUTER
  );
  
  $form['fieldset_liste_appels']['boutton_liste_appels_CHIMIE_TIMTEX'] = array (
      '#value' => t('Appels CHIMIE - TIMTex'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_liste_appels_CHIMIE_TIMTEX')  /////JUSTE RAJOUTER
  );
  
  $form['fieldset_liste_appels']['boutton_liste_appels_INGENIERIE_GENERALE'] = array (
      '#value' => t('Appels Ingénierie Générale'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_liste_appels_INGENIERIE_GENERALE')  /////JUSTE RAJOUTER
  );
  
  
  

  //FIELD REPORTING
  $form['fieldset_reporting'] = array (
      '#type' => 'fieldset',
      '#title' => 'Reporting',
      '#weight' => 2, 
      '#collapsible' => TRUE, 
      '#collapsed' => FALSE,
  );

   $form['fieldset_reporting']['boutton_reporting_appel_mois_dep'] = array (
      '#value' => t('Appel/Mois/Departement'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_reporting_appel_mois_dep')  /////JUSTE RAJOUTER
  );
   
  $form['fieldset_reporting']['boutton_reporting_appel_mois_int'] = array (
      '#value' => t('Appel/Mois/Intéressement'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_reporting_appel_mois_int')  /////JUSTE RAJOUTER
  );
  
  $form['fieldset_reporting']['boutton_reporting_appel_int'] = array (
      '#value' => t('Appel/Intéressement'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_reporting_appel_int')  /////JUSTE RAJOUTER
  );
  
  $form['fieldset_reporting']['boutton_reporting_courrier_plaq_rdv'] = array (
      '#value' => t('Courrier/Plaquette/RDV'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_reporting_courrier_plaq_rdv')  /////JUSTE RAJOUTER
  );
   
   
  
  //FIELD GESTION DES RAPPELS
  $form['fieldset_rappel'] = array (
      '#type' => 'fieldset',
      '#title' => 'Rappel',
      '#weight' => 3, 
      '#collapsible' => TRUE, 
      '#collapsed' => FALSE,
  );
   
   $form['fieldset_rappel']['boutton_rappel'] = array (
      '#value' => t('Consulter les rappels'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_rappel')  /////JUSTE RAJOUTER
  );
     
   
   
   
   //FIELD ADMINISTRER BDD
    $form['fieldset_admin_bdd'] = array (
        '#type' => 'fieldset',
        '#title' => 'Administrer la BDD',
        '#weight' => 4, 
        '#collapsible' => TRUE, 
        '#collapsed' => FALSE,
    ); 
   
    $form['fieldset_admin_bdd']['boutton_administrer_appels'] = array (
      '#value' => t('Gérer les appels'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_administrer_appels')  /////JUSTE RAJOUTER
    );
    
    $form['fieldset_admin_bdd']['boutton_administrer_prospecteurs'] = array (
      '#value' => t('Gérer les prospecteurs'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_administrer_prospecteurs')  /////JUSTE RAJOUTER
    );
    
    $form['fieldset_admin_bdd']['boutton_administrer_entreprises'] = array (
      '#value' => t('Gérer les entreprises'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_action_administrer_entreprises')  /////JUSTE RAJOUTER
    );
    
    $form['fieldset_admin_bdd']['boutton_administrer_contact'] = array (
      '#value' => t('Gérer les contacts'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_administrer_contact')  /////JUSTE RAJOUTER
    );
    
    $form['fieldset_admin_bdd']['boutton_administrer_rappel'] = array (
      '#value' => t('Gérer les rappels'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_administrer_rappel')  /////JUSTE RAJOUTER
    );
    
    
    
    //FIELD ARCHIVES
    $form['fieldset_archives'] = array (
        '#type' => 'fieldset',
        '#title' => 'Consulter les  archives',
        '#weight' => 5, 
        '#collapsible' => TRUE, 
        '#collapsed' => FALSE,
    ); 
    
     $form['fieldset_archives']['boutton_consulter_archives'] = array (
      '#value' => t('Consulter les archives'),
      '#type' => 'submit',
      '#submit' => array('bddprospection_consulter_archives')  /////JUSTE RAJOUTER
    );
    
    return $form;
}





// DEFINITION DES ACTIONS SUBMIT

    function bddprospection_action_ajouter_appel($form, &$form_state) {
      $form_state['redirect'] = 'bddprospection/formulaire';
    }

     function bddprospection_action_liste_appel($form, &$form_state) {
      $form_state['redirect'] = 'bddprospection/liste_appel';
    }
    
     function bddprospection_liste_appels_BTP_BAA($form, &$form_state){
      $form_state['redirect'] = 'bddprospection/test';
    }   
   

    
    
    
    function bddprospection_action_reporting_appel_mois_dep($form, &$form_state) {
      // Perform the 2nd action
    }

    function bddprospection_action_reporting_appel_mois_int($form, &$form_state) {
      // Perform the 2nd action
    }

    function bddprospection_action_reporting_appel_int($form, &$form_state) {
      // Perform the 2nd action
    }

    function bddprospection_reporting_courrier_plaq_rdv($form, &$form_state) {
      // Perform the 2nd action
    }
    
    
    
    
    
    
    function bddprospection_action_administrer_prospecteurs($form, &$form_state) {
       $form_state['redirect'] = 'bddprospection/gerer_prospecteurs';
    }











    
    
    
    
    
    
    
    
    
    
    
    



/*******************************************************************************
 *
 * *************************  PAGE AJOUT APPEL *********************************
 * 
********************************************************************************/

function bddprospection_myform(){
$content = drupal_get_form('bddprospection_form');
return $content;
}

//CREATION DU FORMULAIRE AJOUTER UN APPEL
function bddprospection_form(){
  
 
  //Création de fieldset 
  
      // Cadre Entreprise autour des champs
       $form['selection_entreprise'] = array(

         '#type' => 'fieldset', 
         '#title' => t('ENTREPRISE EXISTANTE'), 
         '#weight' => 0, 
         '#collapsible' => TRUE, 
         '#collapsed' => FALSE,
         );
  
    // Cadre Entreprise autour des champs
    $form['entreprise'] = array(

      '#type' => 'fieldset', 
      '#title' => t('ENTREPRISE'), 
      '#weight' => 1, 
      '#collapsible' => TRUE, 
      '#collapsed' => FALSE,
      );

    //Cadre Contact autour des champs
    $form['contact'] = array(
      '#type' => 'fieldset', 
      '#title' => t('CONTACT'), 
      '#weight' => 2, 
      '#collapsible' => TRUE, 
      '#collapsed' => FALSE,
      );

    //Cadre Appel autour des champs
    $form['appel'] = array(
      '#type' => 'fieldset', 
      '#title' => t('APPEL'), 
      '#weight' => 3, 
      '#collapsible' => TRUE, 
      '#collapsed' => FALSE,
      );



//
//Création des différents champs de la page
//

  ////Création des champs Entreprise 
  
  //COMBOBOX -> Entreprises existantes
  $requete_select_selection_entreprise_existante = db_select('bddprospectionprog_entreprise');
  $requete_select_selection_entreprise_existante->fields('bddprospectionprog_entreprise', array('Nom'));
  $execute_selection_entreprise_existante = $requete_select_selection_entreprise_existante->execute();
  $result_selection_entreprise_existante =  $execute_selection_entreprise_existante->fetchAll(PDO::FETCH_ASSOC);
  
  $Liste_entreprise_existante=array();
  
  foreach ($result_selection_entreprise_existante as $cle => $val){
      $Liste_entreprise_existante[] = $val['Nom'];
  }
 
    
  $form['selection_entreprise_liste'] = array(
  '#title' => 'Vérifier si l\'entreprise',
  '#type' => 'select',
  '#options' => $Liste_entreprise_existante,
  );  
    
////Création des champs Entreprise
  $form['entreprise_nom'] = array(
  '#title' => 'Nom de l\'entreprise',
  '#type' => 'textfield',
  '#required' => TRUE,
  );

  $form['entreprise_secteur'] = array(
  '#title' => 'Secteur d\'activité',
  '#type' => 'textfield',
  );

  $form['entreprise_adress'] = array(
  '#title' => 'Adresse',
  '#type' => 'textfield',
  );

  $form['entreprise_cp'] = array(
  '#title' => 'Code Postal',
  '#type' => 'textfield',
  );

  $form['entreprise_ville'] = array(
  '#title' => 'Ville',
  '#type' => 'textfield',
  );

  $form['entreprise_telephone'] = array(
  '#title' => 'Téléphone',
  '#type' => 'textfield',
  );

  $form['entreprise_fax'] = array(
  '#title' => 'Fax',
  '#type' => 'textfield',
  );

  $form['entreprise_mail'] = array(
  '#title' => 'E-mail',
  '#type' => 'textfield',
  );
 
  
  
  
////Création des champs Contact
  $form['contact_nom'] = array(
  '#title' => 'Nom',
  '#type' => 'textfield',
  );

  $form['contact_prenom'] = array(
  '#title' => 'Prénom',
  '#type' => 'textfield',
  );

  $form['contact_fonction'] = array(
  '#title' => 'Fonction',
  '#type' => 'textfield',
  );

  $form['contact_telephone'] = array(
  '#title' => 'Téléphone',
  '#type' => 'textfield',
  );

  $form['contact_portable'] = array(
  '#title' => 'Portable',
  '#type' => 'textfield',
  );

  $form['contact_mail'] = array(
  '#title' => 'E-mail',
  '#type' => 'textfield',
  );
  
    
  
  
  
  
 
  //Création des champs appel
 
   $form['appel_identifiant'] = array(
  '#title' => 'Identifiants HEI',
  '#type' => 'textfield',
  '#description' => t('Ne pas mettre de "h" au début ! Exemple : 10478 ;P'),
  );
  
  
  //Attention la variable date_par_default est utilisée pour tous les champs dates de la page ;P
  $today = getdate();
  $today_formaté = '$today[year]'.'-'.'$today[mon]'.'-'.'$today[mday]';
  
  $format_date_appel = 'Y-m-d';
  $form['appel_date_appel'] = array(
     '#type' => 'date_text', // types 'date_select' and 'date_timezone' are also supported. See .inc file.
     '#title' => t('Sélectionner la date de l\'appel'),
     '#default_value' => $today_formaté, 
     '#date_format' => $format_date_appel,
     '#date_label_position' => 'within', // See other available attributes and what they do in date_api_elements.inc
     '#date_timezone' => 'Europe/Paris',
     '#date_year_range' => '0:+15',
  );
 
  //COMBOBOX
  $form['appel_appreciation'] = array(
  '#title' => 'Appréciation',
  '#type' => 'select',
  '#options' => array(
         0 => t('Pas de réponse'),
         1 => t('Pas intéressée'),
         2 => t('Intéressée'),
         3 => t('Très intéressée'),
         ),
  );

  //COMBOBOX
  $form['appel_relance'] = array(
  '#title' => 'Relance',
  '#type' => 'select',
  '#options' => array(
         0 => t('Jamais'),
         1 => t('Dans plus d\'un an'),
         2 => t('D\'ici trois mois à un an'),
         3 => t('Dans moins de trois mois'),
         4 => t('Rapidement'),
         ),
  );

  $form['appel_courriel_envoye'] = array(
  '#type' => 'checkbox',
  '#title' => t('Courriel envoyé'),
  '#options' => array(
         0 => '0',
         1 => '1',
   ),
  );
  
  $form['appel_plaquette_envoye'] = array(
  '#type' => 'checkbox',
  '#title' => t('Plaquette envoyée'),
  '#options' => array(
         0 => '0',
         1 => '1',
   ),
  );
  
  $form['appel_rendez_vous_obtenu'] = array(
  '#type' => 'checkbox',
  '#title' => t('Rendez-vous obtenu'),
  '#options' => array(
         0 => '0',
         1 => '1',
   ),
  );
  
  //Création d'un champ date  
  $format_date_rdv = 'Y-m-d';
  $form['appel_date_rendez_vous'] = array(
     '#type' => 'date_text', // types 'date_select' and 'date_timezone' are also supported. See .inc file.
     '#title' => t('Date du rendez-vous'),
     '#default_value' => $today_formaté,
     '#date_format' => $format_date_rdv,
     '#date_label_position' => 'within', // See other available attributes and what they do in date_api_elements.inc
     '#date_timezone' => 'Europe/Paris',
     '#date_year_range' => '0:+15',
  );
  
   $form['appel_remarques'] = array(
   '#title' => 'Remarques Complémentaires',
   '#type' => 'textarea',
   );
  
  
  
   
  
  
//
//Attribution des champs créés à leur fieldset
//
   

////Attribution Fieldset Sélection_entreprise
    $form['selection_entreprise']['selection_entreprise_liste'] = $form['selection_entreprise_liste'];
    unset($form['selection_entreprise_liste']);
   
////Attributions Fieldset entreprise
    $form['entreprise']['entreprise_nom'] = $form['entreprise_nom'];
    unset($form['entreprise_nom']);

    $form['entreprise']['entreprise_secteur'] = $form['entreprise_secteur'];
    unset($form['entreprise_secteur']);

    $form['entreprise']['entreprise_adress'] = $form['entreprise_adress'];
    unset($form['entreprise_adress']);

    $form['entreprise']['entreprise_cp'] = $form['entreprise_cp'];
    unset($form['entreprise_cp']);

    $form['entreprise']['entreprise_ville'] = $form['entreprise_ville'];
    unset($form['entreprise_ville']);

    $form['entreprise']['entreprise_telephone'] = $form['entreprise_telephone'];
    unset($form['entreprise_telephone']);

    $form['entreprise']['entreprise_fax'] = $form['entreprise_fax'];
    unset($form['entreprise_fax']);

    $form['entreprise']['entreprise_mail'] = $form['entreprise_mail'];
    unset($form['entreprise_mail']);

    
    ////Attributions Fieldset contact
  
    $form['contact']['contact_nom'] = $form['contact_nom'];
    unset($form['contact_nom']);
    
    $form['contact']['contact_prenom'] = $form['contact_prenom'];
    unset($form['contact_prenom']);
    
    $form['contact']['contact_fonction'] = $form['contact_fonction'];
    unset($form['contact_fonction']);
    
    $form['contact']['contact_telephone'] = $form['contact_telephone'];
    unset($form['contact_telephone']);
    
    $form['contact']['contact_portable'] = $form['contact_portable'];
    unset($form['contact_portable']);
    
    $form['contact']['contact_mail'] = $form['contact_mail'];
    unset($form['contact_mail']);
        
    
    
    
    //Attributions Fieldset appel
      
    $form['appel']['appel_identifiant']= $form['appel_identifiant'];
    unset($form['appel_identifiant']);
      
    $form['appel']['appel_date_appel'] = $form['appel_date_appel'];
    unset($form['appel_date_appel']);
    
    $form['appel']['appel_appreciation'] = $form['appel_appreciation'];
    unset($form['appel_appreciation']);
    
    $form['appel']['appel_relance'] = $form['appel_relance'];
    unset($form['appel_relance']);
    
    $form['appel']['appel_courriel_envoye'] = $form['appel_courriel_envoye'];
    unset($form['appel_courriel_envoye']);
    
    $form['appel']['appel_plaquette_envoye'] = $form['appel_plaquette_envoye'];
    unset($form['appel_plaquette_envoye']);
    
    $form['appel']['appel_rendez_vous_obtenu'] = $form['appel_rendez_vous_obtenu'];
    unset($form['appel_rendez_vous_obtenu']);
    
    $form['appel']['appel_date_rendez_vous'] = $form['appel_date_rendez_vous'];
    unset($form['appel_date_rendez_vous']);
    
    $form['appel']['appel_remarques'] = $form['appel_remarques'];
    unset($form['appel_remarques']);
    


$form['valider'] = array(
'#type' => 'submit',
'#value' => t('Soumettre'),
'#weight' => 4,
);

return $form;
}


//
////FONCTION DE SOUMISSION DES DONNEES
//  

    //Action générées après avoir appuyé sur le bouton submit

    function bddprospection_form_submit($form, &$form_state){
    $query_entreprise = db_insert('bddprospectionprog_entreprise');

    $query_entreprise
    ->fields(array(
      'Nom'=>$form_state['values']['entreprise_nom'],
      'Secteur_activite'=>$form_state['values']['entreprise_secteur'],
      'Adresse'=>$form_state['values']['entreprise_adress'],
      'Code_Postal'=>$form_state['values']['entreprise_cp'],
      'Ville'=>$form_state['values']['entreprise_ville'],
      'Telephone'=>$form_state['values']['entreprise_telephone'],
      'Fax'=>$form_state['values']['entreprise_fax'],
      'Mail'=>$form_state['values']['entreprise_mail'],
      ))
        
    ->execute();
 
    
    $query_contact = db_insert('bddprospectionprog_contact');
    $query_contact
    ->fields(array(
      'Entreprise'=>$form_state['values']['entreprise_nom'],
      'Nom'=>$form_state['values']['contact_nom'],
      'Prenom'=>$form_state['values']['contact_prenom'],
      'Fonction'=>$form_state['values']['contact_fonction'],
      'Telephone'=>$form_state['values']['contact_telephone'],
      'Portable'=>$form_state['values']['contact_portable'],
      'Mail'=>$form_state['values']['entreprise_mail'],
      ))
        
    ->execute();
    
    
    //
    
    $appreciation="Pas de réponse";
    switch($form_state['values']['appel_appreciation']){
      case 1:
         $appreciation="Pas intéressée";
      case 2:
         $appreciation="Intéressée";
      case 3:
         $appreciation="Très intéressée";
    }
    
    $relance="Jamais";
    switch($form_state['values']['appel_relance']){
      case 0:
         $relance="Jamais";
      case 1:
         $relance="Dans plus d\'un an";
      case 2:
         $relance="D\'ici trois mois à un an";
      case 3:
         $relance="Dans moins de trois mois";
      case 4:
         $relance="Rapidement";
    }
    
    
    
    
    
    $query_appel = db_insert('bddprospectionprog_appel');
    $query_appel
    ->fields(array(
      'Date_appel'=>$form_state['values']['appel_date_appel'],
      'Etudiant'=>$form_state['values']['appel_identifiant'],                   /////RECUPERER LE # courant! 
      'Entreprise'=>$form_state['values']['entreprise_nom'],
      'Contact'=>$form_state['values']['contact_nom'],
      'Appreciation'=>$appreciation,
      'Relance'=>$relance,
      'Courriel_envoye'=>$form_state['values']['appel_courriel_envoye'],
      'Plaquette_envoyee'=>$form_state['values']['appel_plaquette_envoye'],
      'Rendez_vous_obtenu'=>$form_state['values']['appel_rendez_vous_obtenu'],
      'Date_rendez_vous'=>$form_state['values']['appel_date_rendez_vous'],
      'Remarques_complementaires'=>$form_state['values']['appel_remarques'],    //// Limiter à 255 caractères
      'Rappele'=>'0',
      ))

    ->execute();
    
    }


    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
/*******************************************************************************
 *
 * *************************  PAGE LISTE APPEL *********************************
 * 
********************************************************************************/
    
    
    
function bddprospection_liste_appel_generale(){
  
$query = db_select('drupal','bddprospectionprog_appel');
$query->join('bddprospectionprog_entreprise','Telephone','bddprospectionprog_appel.Entreprise=bddprospectionprog_entreprise.Nom');
$query->join('bddprospectionprog_entreprise','Mail','bddprospectionprog_appel.Entreprise=bddprospectionprog_entreprise.Nom');
$query->join('bddprospectionprog_contact','Fonction','bddprospectionprog_appel.Entreprise=bddprospectionprog_contact.Entreprise');
$query->join('bddprospectionprog_contact','Portable','bddprospectionprog_appel.Entreprise=bddprospectionprog_contact.Entreprise');
$query->join('bddprospectionprog_contact','Mail','bddprospectionprog_appel.Entreprise=bddprospectionprog_contact.Entreprise');
$query->join('bddprospectionprog_prospecteur','Nom','bddprospectionprog_appel.Etudiant=bddprospectionprog_prospecteur.Matricule_HEI');
$query->join('bddprospectionprog_prospecteur','Departement','bddprospectionprog_appel.Etudiant=bddprospectionprog_prospecteur.Matricule_HEI');


$query->fields('bddprospectionprog_appel', array(
  'Date_appel',
  'Entreprise'
  ))
  
    ->field('bddprospectionprog_entreprise',array(
     'Telephone',
     'Mail',
    ))
    
    -> field('bddprospectionprog_appel', array(
     'Contact',
    ))
  
    ->field('bddprospectionprog_contact',array(
     'Fonction',
     'Portable',
    ))
    
    ->field('bddprospectionprog_prospecteur',array(
      'Nom',
      'Departement',
    ))
    
    ->fields('bddprospectionprog_appel', array(
      'Appreciation',
      'Relance'
    ))
 
    ->field('bddprospectionprog_contact',array(
     'Mail',
    ));                  

 
$result = $query->execute();
foreach ($result as $record) {
dpm($record);
}
  
  
  
}
    
    
    






















    
    
/*******************************************************************************
 *
 * **********************  PAGE LISTE APPEL BTP ********************************
 * 
********************************************************************************/
  
    
    
    function bddprospection_liste_appel_btp(){
      
//      function bddprospection_form_submit($form, &$form_state){
//
//$query = db_select('bddprospectionprog_prospecteurs');
// 
//$query
//->fields('bddprospectionprog_prospecteurs', array('Matricule_HEI','Nom', 'Prenom','Mandat','Classe','Telephone','Departement','Directeur_de_departement'))
//->range(0, 50);
// 
//$result = $query->execute();
//foreach ($result as $record) {
//dpm($record);
//}
//}
      
      
  
    }    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
/*******************************************************************************
 *
 * ***********  PAGE ADMINISTRER BDD / GERER PROSPECTEURS **********************
 * 
********************************************************************************/
 
    
    
 function bddprospection_gerer_prospecteurs(){
   $content = drupal_get_form('bddprospection_gerer_prospecteurs_form');
   return $content;
   
 }   
    
    
 function bddprospection_gerer_prospecteurs_form(){
  

//FIELD Gérer propsecteurs
    $form['fieldset_gerer_prospecteurs'] = array (
        '#type' => 'fieldset',
        '#title' => 'Gerer les prospecteurs',
        '#weight' => 0, 
        '#collapsible' => TRUE, 
        '#collapsed' => FALSE,
    );
    
     $form['fieldset_gerer_prospecteurs']['boutton_consulter_prospecteurs'] = array (
        '#value' => t('Consulter la liste des prospecteurs'),
        '#type' => 'submit',
        '#submit' => array('bddprospection_action_consulter_prospecteurs') 
    );
    
    $form['fieldset_gerer_prospecteurs']['boutton_ajout_prospecteurs'] = array (
        '#value' => t('Ajouter un prospecteurs'),
        '#type' => 'submit',
        '#submit' => array('bddprospection_action_ajouter_prospecteurs') 
    );
    
    $form['fieldset_gerer_prospecteurs']['boutton_mise_a_jour_prospecteurs'] = array (
        '#value' => t('Mettre a jour'),
        '#type' => 'submit',
        '#submit' => array('bddprospection_action_mettre_a_jour__prospecteurs') 
    );
    
    $form['fieldset_gerer_prospecteurs']['boutton_supprimer_prospecteur'] = array (
        '#value' => t('Supprimer un prospecteurs'),
        '#type' => 'submit',
        '#submit' => array('bddprospection_action_supprimer_prospecteurs') 
    );
   
   
    function bddprospection_action_consulter_prospecteurs($form, &$form_state) {
      $form_state['redirect'] = 'bddprospection/consulter_prospecteurs';
    }
    
    function bddprospection_action_ajouter_prospecteurs($form, &$form_state) {
      $form_state['redirect'] = 'bddprospection/ajout_prospecteurs';
    }
    
    function bddprospection_action_mettre_a_jour__prospecteurs($form, &$form_state) {
      $form_state['redirect'] = 'bddprospection/maj_prospecteurs';
    }
    
    function bddprospection_action_supprimer_prospecteurs($form, &$form_state) {
      $form_state['redirect'] = 'bddprospection/supprimer_prospecteurs';
    }
    
    return $form;
    
 }   
    
    
    
    
    
    
        
    //PAGE CONSULTER PROSPECTEURS
    
    function bddprospection_consulter_prospecteurs() {

  # configure the table header columns
  $header = array(
    array('data' => 'Matricule',        'field' => 'Matricule_HEI',               'sort' => 'ASC'),
    array('data' => 'Nom',              'field' => 'Nom',                         'sort' => 'ASC'),
    array('data' => 'Prenom',           'field' => 'Prenom',                      'sort' => 'ASC'),
    array('data' => 'Mandat',           'field' => 'Mandat',                      'sort' => 'ASC'),
    array('data' => 'Classe',           'field' => 'Classe',                      'sort' => 'ASC'),
    array('data' => 'Telephone',        'field' => 'Telephone',                   'sort' => 'ASC'),
    array('data' => 'Departement',      'field' => 'Departement',                 'sort' => 'ASC'),
    array('data' => 'Responsable',      'field' => 'Directeur_de_departement',    'sort' => 'ASC'),
 
  );

  # set the database table and initial SelectQuery options
  # $select is a SelectQuery object.
  # @see http://api.drupal.org/api/drupal/includes--database--select.inc/class/Se...
  $select = db_select('bddprospectionprog_prospecteurs','p')
              ->extend('PagerDefault')
              ->extend('TableSort');

  # get the desired fields
  # orderByHeader is a TableSort method (http://api.drupal.org/api/drupal/includes--tablesort.inc/function/TableS...)
  $select->fields('p', array('Matricule_HEI', 'Nom', 'Prenom', 'Mandat', 'Classe','Telephone','Departement','Directeur_de_departement'))
         ->limit(20)
         ->orderByHeader($header)
         ->orderBy('Matricule_HEI', 'DESC');  # TODO this call seems to be losing to orderByHeader on page load

  # execute the query
  $results = $select->execute();

  # configure the table rows, making the first column a link to our 'edit' page
  $rows = array();
  foreach ($results as $row) {
    $rows[] = array($row->Matricule_HEI,                           
                    $row->Nom,
                    $row->Prenom,
                    $row->Mandat,
                    $row->Classe,
                    $row->Telephone,
                    $row->Departement,
                    $row->Directeur_de_departement,
    );
  }

  $output = theme('table', array('header' => $header,
                                 'rows' => $rows ));

  # add the pager
  $output .= theme('pager');

  return $output;

}
   


    //PAGE AJOUTER UN PROSPECTEUR
    function bddprospection_ajouter_prospecteurs(){
      $content = drupal_get_form('bddprospection_ajouter_prospecteurs_form');
      return $content;
      
    }


    function bddprospection_ajouter_prospecteurs_form(){
      
       $form['ajouter_prospecteurs_Matricule'] = array(
        '#title' => 'Matricule',
        '#type' => 'textfield',
        '#required' => TRUE, 
       );
      
      
      $form['ajouter_prospecteurs_Nom'] = array(
        '#title' => 'Nom',
        '#type' => 'textfield',
      
      );
      
      
      $form['ajouter_prospecteurs_Prenom'] = array(
        '#title' => 'Prenom',
        '#type' => 'textfield',
       
      );
      
      
      $form['ajouter_prospecteurs_Mandat'] = array(
        '#title' => 'Mandat',
        '#type' => 'textfield',
      
      );
      
      
      $form['ajouter_prospecteurs_Classe'] = array(
        '#title' => 'Classe',
        '#type' => 'textfield',
      
      );
      
      
      $form['ajouter_prospecteurs_Telephone'] = array(
        '#title' => 'Telephone',
        '#type' => 'textfield',
      
      );
      
      
      $form['ajouter_prospecteurs_Departement'] = array(
        '#title' => 'Departement',
        '#type' => 'textfield',
      
      );
      
      
     
      $requete_select_liste_etudiant = db_select('bddprospectionprog_prospecteurs');
      $requete_select_liste_etudiant->fields('bddprospectionprog_prospecteurs', array('Nom'));
      $execute_select_liste_etudiant = $requete_select_liste_etudiant->execute();
      $result_select_liste_etudiant =  $execute_select_liste_etudiant->fetchAll(PDO::FETCH_ASSOC);

      $Liste_etudiants=array();

      foreach ($result_select_liste_etudiant as $cle => $val){
          $Liste_etudiants[] = $val['Nom'];
      }


      $form['ajouter_prospecteurs_Responsable'] = array(
      '#title' => 'Responsable',
      '#type' => 'select',
      '#options' => $Liste_etudiants,
      ); 
      
      
           
      $form['valider'] = array(
        '#type' => 'submit',
        '#value' => t('Soumettre'),
        '#weight' => 4,
        '#submit' => array('bddprospection_ajouter_prospecteurs_submit')
      );
      
      
      return $form;
      
    }
    
    
    
    
    
    function bddprospection_ajouter_prospecteurs_submit($form, &$form_state){
      
      $query_ajout_prospecteur = db_insert('bddprospectionprog_prospecteurs');

    $query_ajout_prospecteur
    ->fields(array(
      'Matricule_HEI'=>$form_state['values']['ajouter_prospecteurs_Matricule'],
      'Nom'=>$form_state['values']['ajouter_prospecteurs_Nom'],
      'Prenom'=>$form_state['values']['ajouter_prospecteurs_Prenom'],
      'Mandat'=>$form_state['values']['ajouter_prospecteurs_Mandat'],
      'Classe'=>$form_state['values']['ajouter_prospecteurs_Classe'],
      'Telephone'=>$form_state['values']['ajouter_prospecteurs_Telephone'],
      'Departement'=>$form_state['values']['ajouter_prospecteurs_Departement'],
      'Directeur_de_departement'=>$form_state['values']['ajouter_prospecteurs_Responsable'],
      ))
        
    ->execute();
      
      
    }
    
    
    
    
       
    
    
    
    

    //PAGE MAJ PROSPECTEURS
    
    function bddprospection_mettre_a_jour_prospecteurs(){
      $content = drupal_get_form('bddprospection_mettre_a_jour_prospecteurs_form');
      return $content;
    }
    
       
    
    function bddprospection_mettre_a_jour_prospecteurs_form(){
    
     
      $requete_select_liste_etudiant = db_select('bddprospectionprog_prospecteurs');
      $requete_select_liste_etudiant->fields('bddprospectionprog_prospecteurs', array('Nom'));
      $execute_select_liste_etudiant = $requete_select_liste_etudiant->execute();
      $result_select_liste_etudiant =  $execute_select_liste_etudiant->fetchAll(PDO::FETCH_ASSOC);

      $Liste_etudiants=array();

      foreach ($result_select_liste_etudiant as $cle => $val){
          $Liste_etudiants[] = $val['Nom'];
      }

      $form['mettre_a_jour_prospecteurs_Nom'] = array(
      '#title' => 'Nom',
      '#type' => 'select',
      '#options' => $Liste_etudiants,
      ); 
      
      
      $form['valider'] = array(
        '#type' => 'submit',
        '#value' => t('Charger les données du prospecteur'),
        '#weight' => 4,
        '#submit' => array('bddprospection_ajouter_prospecteurs_submit')
      );
      
      
      
      
      
      
      
      
      
      
      
      $form['mettre_a_jour_prospecteurs_Prenom'] = array(
        '#title' => 'Prenom',
        '#type' => 'textfield',
        '#default_value' => '',
      );
      
      $form['mettre_a_jour_prospecteurs_Matricule'] = array(
        '#title' => 'Matricule',
        '#type' => 'textfield',
        '#default_value' => '',
      );
      
      
      
      
      $form['mettre_a_jour_prospecteurs_Mandat'] = array(
        '#title' => 'Mandat',
        '#type' => 'textfield',
        '#default_value' => '',
      );
      
      
      $form['mettre_a_jour_prospecteurs_Classe'] = array(
        '#title' => 'Classe',
        '#type' => 'textfield',
        '#default_value' => '',
      );
      
      
      $form['mettre_a_jour_prospecteurs_Telephone'] = array(
        '#title' => 'Telephone',
        '#type' => 'textfield',
        '#default_value' => '',
      );
      
      
      $form['mettre_a_jour_prospecteurs_Departement'] = array(
        '#title' => 'Departement',
        '#type' => 'textfield',
        '#default_value' => '',
      );
      
      
      $form['mettre_a_jour_prospecteurs_Responsable'] = array(
        '#title' => 'Responsable',
        '#type' => 'textfield',
        '#default_value' => '',
      );
      
      
      $form['valider'] = array(
        '#type' => 'submit',
        '#value' => t('Soumettre'),
        '#weight' => 4,
        '#submit' => array('bddprospection_effectuer_mise_a_jour_prospecteurs_submit')
      );
        
      
      return $form;
      
    }
    
  
    
    function bddprospection_effectuer_mise_a_jour_prospecteurs_submit($form, &$form_state){
      
      db_update('bddprospectionprog_prospecteurs') ->fields( 
        array( 
          'Matricule_HEI' => $form_state['values']['mettre_a_jour_prospecteurs_Matricule'], 
          'Nom' => $form_state['values']['mettre_a_jour_prospecteurs_Nom'], 
          'Prenom' => $form_state['values']['mettre_a_jour_prospecteurs_Prenom'], 
          'Mandat' => $form_state['values']['mettre_a_jour_prospecteurs_Mandat'], 
          'Classe' => $form_state['values']['mettre_a_jour_prospecteurs_Classe'], 
          'Telephone' => $form_state['values']['mettre_a_jour_prospecteurs_Telephone'], 
          'Departement' => $form_state['values']['mettre_a_jour_prospecteurs_Departement'], 
          'Directeur_de_departement' => $form_state['values']['mettre_a_jour_prospecteurs_Responsable'], 
        ) 
      ) ->execute();
      
    }
    
    
    
    
    
    
    
    function bddprospection_supprimer_propsecteur(){
      
      
    }
    
    
    
    
    
    
    
//    function myform_form_submit($form, &$form_state) {
//    if($form_state['clicked_button']['#value'] == $form_state['values']['submit_one'])	  //if button 1 is clicked
//        $form_state['redirect'] = 'formulaire';	//redirect to whatever page you want
//    else if($form_state['clicked_button']['#value'] == $form_state['values']['submit_two'])  //if button 2 is clicked
//        $form_state['redirect'] = 'bddprospection/formulaire';
//    }
    
    
    

    
    
    
    

//ENVOI DU FORMULAIRE
//http://drupalfr.org/node/8337
//function mon_formulaire_submit($form, &$form_state){
//  variable_set(blablabla);
//  drupal_set_message($form_state['values']['nom']);
//  $form_state['redirect'] = 'node'; // on redirige l'utilisateur sur la page de notre choix !
//}




//function bddprospection_form_submit($form, &$form_state){
//$query = db_insert('bddprospectionprog_entreprise');
//
//$query
//->fields(array(
//  'Nom'=>$form['nom'],
//  'Secteur_activite'=>$form['secteur'],
//  'Adresse'=>$form['adress'],
//  'Code_Postal'=>$form['cp'],
//  'Ville'=>$form['ville'],
//  'Telephone'=>$form['telephone'],
//  'Fax'=>$form['fax'],
//  'Mail'=>$form['mail'],
//  ))
//    
//->execute();
//}


//function bddprospection_form_submit($form, &$form_state){
//
//$query = db_select('bddprospectionprog_prospecteurs');
// 
//$query
//->fields('bddprospectionprog_prospecteurs', array('Matricule_HEI','Nom', 'Prenom','Mandat','Classe','Telephone','Departement','Directeur_de_departement'))
//->range(0, 50);
// 
//$result = $query->execute();
//foreach ($result as $record) {
//dpm($record);
//}
//}







//Exemple de validation

//function form_example_tutorial_6_validate($form, &$form_state) {
//  $year_of_birth = $form_state['values']['year_of_birth'];
//  if ($year_of_birth && ($year_of_birth < 1900 || $year_of_birth > 2000)) {
//    form_set_error('year_of_birth', t('Enter a year between 1900 and 2000.'));
//  }
//}



//Exemple de set message
//drupal_set_message('La variable persistante est inchangée');